var canvas = document.getElementById("myCanvas");
var color = "red";
var ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = "blue";
ctx.lineWidth = 5;
ctx.arc(300,200,40,0,2 * Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "black";
ctx.lineWidth = 5;
ctx.arc(400,200,40,0,2 * Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "gold";
ctx.lineWidth = 5;
ctx.arc(350,230,40,0,2 * Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "green";
ctx.lineWidth = 5;
ctx.arc(450,230,40,0,2 * Math.PI);
ctx.stroke();ctx.beginPath();
ctx.strokeStyle = "red";
ctx.lineWidth = 5;
ctx.arc(500,200,40,0,2 * Math.PI);
ctx.stroke();